cc_test(
    name = "bit_vector",
    size = "small",
    srcs = ["bit_vector.cpp"],
    visibility = ["//main:__pkg__"],
    deps = [
        "//simd",
        "@gtest//:main",
    ],
)

cc_test(
    name = "view",
    size = "small",
    srcs = ["view.cpp"],
    visibility = ["//main:__pkg__"],
    deps = [
        "//simd",
        "@gtest//:main",
    ],
)

cc_test(
    name = "dot_product",
    size = "small",
    srcs = ["math/dot_product.cpp"],
    visibility = ["//main:__pkg__"],
    deps = [
        "//simd",
        "@gtest//:main",
    ],
)
