cc_test(
    name = "bit_vector",
	size = "small",
    srcs = ["bit_vector.cpp"],
    deps = [
        "//simd",
        "@gtest//:main"
    ],
    visibility = ["//main:__pkg__"]
)

cc_test(
    name = "byte_view",
	size = "small",
    srcs = ["byte_view.cpp"],
    deps = [
        "//simd",
        "@gtest//:main"
    ],
    visibility = ["//main:__pkg__"]
)

cc_test(
    name = "vector",
	size = "small",
    srcs = ["math/vector.cpp"],
    deps = [
        "//simd",
        "@gtest//:main"
    ],
    visibility = ["//main:__pkg__"]
)
